[package]
name = "gpu-scratch"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["macros", "rt", "sync"] }
wgpu = "26.0.1"
